---
driver:
  name: vagrant
  require_chef_omnibus: true
  customize:
    cpus: 4
    memory: 1536

provisioner:
  name: chef_solo
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/.chef/encrypted_data_bag_secret
  data_bags_path: <%= ENV['CHEF_REPO'] %>/data_bags

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[s3_dir::default]
