name             's3_dir_test'
maintainer       'EverTrue, Inc.'
maintainer_email 'devops@evertrue.com'
license          'Apache v2.0'
description      'Installs/Configures s3_dir test cookbook'
long_description 'Installs/Configures s3_dir test cookbook'
version          '1.0.1'

depends 'python'
depends 's3_dir'
